"""create topics table

Revision ID: 07568a53edf0
Revises: 8e1b19a7ac18
Create Date: 2026-07-06 11:00:02.916461

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from pgvector.sqlalchemy import VECTOR

# revision identifiers, used by Alembic.
revision: str = '07568a53edf0'
down_revision: Union[str, Sequence[str], None] = '8e1b19a7ac18'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('topics',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('summary', sa.String(), nullable=True),
    sa.Column('embedding', VECTOR(dim=1536), nullable=True),
    sa.Column('importance', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_topics_title'), 'topics', ['title'], unique=True)
    op.add_column('tabs', sa.Column('topic_id', sa.String(), nullable=True))
    op.create_foreign_key(None, 'tabs', 'topics', ['topic_id'], ['id'])
    op.drop_column('tabs', 'topic')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tabs', sa.Column('topic', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_constraint('', 'tabs', type_='foreignkey')
    op.drop_column('tabs', 'topic_id')
    op.drop_index(op.f('ix_topics_title'), table_name='topics')
    op.drop_table('topics')
    # ### end Alembic commands ###
