"""add user foreign key

Revision ID: 586fbc59f9d6
Revises: 96f9ead2d5b8
Create Date: 2026-06-15 15:18:20.342504

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '586fbc59f9d6'
down_revision: Union[str, Sequence[str], None] = '96f9ead2d5b8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'tabs', 'users', ['user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'tabs', type_='foreignkey')
    # ### end Alembic commands ###
