"""add favicon to tabs

Revision ID: 7a5454de22ff
Revises: e67f11899bfa
Create Date: 2026-06-16 14:05:01.768825

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7a5454de22ff'
down_revision: Union[str, Sequence[str], None] = 'e67f11899bfa'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tabs', sa.Column('favicon', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tabs', 'favicon')
    # ### end Alembic commands ###
