"""message importance

Revision ID: 8e1b19a7ac18
Revises: d40cdf6f45c2
Create Date: 2026-07-05 12:55:20.691242

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8e1b19a7ac18'
down_revision: Union[str, Sequence[str], None] = 'd40cdf6f45c2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('messages', sa.Column('importance', sa.Float(), nullable=False, server_default="0"))
    op.alter_column("messages", "importance", server_default=None)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('messages', 'importance')
    # ### end Alembic commands ###
