"""create tab_chunks table

Revision ID: 95ddee540a81
Revises: 7a5454de22ff
Create Date: 2026-06-17 20:28:51.650692

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

from pgvector.sqlalchemy import VECTOR

# revision identifiers, used by Alembic.
revision: str = '95ddee540a81'
down_revision: Union[str, Sequence[str], None] = '7a5454de22ff'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tab_chunk',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('tab_id', sa.String(), nullable=False),
    sa.Column('chunk_text', sa.Text(), nullable=False),
    sa.Column('embedding', VECTOR(384), nullable=False),
    sa.ForeignKeyConstraint(['tab_id'], ['tabs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tab_chunk_tab_id'), 'tab_chunk', ['tab_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_tab_chunk_tab_id'), table_name='tab_chunk')
    op.drop_table('tab_chunk')
    # ### end Alembic commands ###
