"""add entity graph

Revision ID: b26c4e4dbf0e
Revises: 07568a53edf0
Create Date: 2026-07-06 17:12:49.312155

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

from pgvector.sqlalchemy import VECTOR

# revision identifiers, used by Alembic.
revision: str = 'b26c4e4dbf0e'
down_revision: Union[str, Sequence[str], None] = '07568a53edf0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('entities',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('entity_type', sa.String(), nullable=False),
    sa.Column('summary', sa.String(), nullable=True),
    sa.Column('embedding', VECTOR(dim=1536), nullable=True),
    sa.Column('importance', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_entities_entity_type'), 'entities', ['entity_type'], unique=False)
    op.create_index(op.f('ix_entities_name'), 'entities', ['name'], unique=True)
    op.create_table('entity_aliases',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('alias', sa.String(), nullable=False),
    sa.Column('entity_id', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['entity_id'], ['entities.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_entity_aliases_alias'), 'entity_aliases', ['alias'], unique=True)
    op.create_index(op.f('ix_entity_aliases_entity_id'), 'entity_aliases', ['entity_id'], unique=False)
    op.create_table('tab_entities',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('tab_id', sa.String(), nullable=False),
    sa.Column('entity_id', sa.String(), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('mention_count', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['entity_id'], ['entities.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tab_id'], ['tabs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tab_entities_entity_id'), 'tab_entities', ['entity_id'], unique=False)
    op.create_index(op.f('ix_tab_entities_tab_id'), 'tab_entities', ['tab_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_tab_entities_tab_id'), table_name='tab_entities')
    op.drop_index(op.f('ix_tab_entities_entity_id'), table_name='tab_entities')
    op.drop_table('tab_entities')
    op.drop_index(op.f('ix_entity_aliases_entity_id'), table_name='entity_aliases')
    op.drop_index(op.f('ix_entity_aliases_alias'), table_name='entity_aliases')
    op.drop_table('entity_aliases')
    op.drop_index(op.f('ix_entities_name'), table_name='entities')
    op.drop_index(op.f('ix_entities_entity_type'), table_name='entities')
    op.drop_table('entities')
    # ### end Alembic commands ###
