"""add conversations and messages

Revision ID: c85355221184
Revises: d7d9cced8664
Create Date: 2026-06-25 11:25:16.895921

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

from pgvector.sqlalchemy import Vector

# revision identifiers, used by Alembic.
revision: str = 'c85355221184'
down_revision: Union[str, Sequence[str], None] = 'd7d9cced8664'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('conversations',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('title', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_conversations_user_id'), 'conversations', ['user_id'], unique=False)
    op.create_table('messages',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('conversation_id', sa.String(), nullable=False),
    sa.Column('role', sa.String(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['conversation_id'], ['conversations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_messages_conversation_id'), 'messages', ['conversation_id'], unique=False)
    op.alter_column('memory_clusters', 'embedding',
               existing_type= Vector(384),
               nullable=False)
    op.alter_column('tab_relationships', 'source_tab_id',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('tab_relationships', 'related_tab_id',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('tab_relationships', 'similarity_score',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('tab_relationships', 'similarity_score',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=True)
    op.alter_column('tab_relationships', 'related_tab_id',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('tab_relationships', 'source_tab_id',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('memory_clusters', 'embedding',
               existing_type= Vector(384),
               nullable=True)
    op.drop_index(op.f('ix_messages_conversation_id'), table_name='messages')
    op.drop_table('messages')
    op.drop_index(op.f('ix_conversations_user_id'), table_name='conversations')
    op.drop_table('conversations')
    # ### end Alembic commands ###
