"""memory importance

Revision ID: d40cdf6f45c2
Revises: d48f8f999aa0
Create Date: 2026-07-04 14:12:26.993464

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd40cdf6f45c2'
down_revision: Union[str, Sequence[str], None] = 'd48f8f999aa0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tabs', sa.Column('importance_score', sa.Float(), nullable=False, server_default="50"))
    op.add_column('tabs', sa.Column('open_count', sa.Integer(), nullable=False, server_default="1"))
    op.add_column('tabs', sa.Column('total_time_spent', sa.Integer(), nullable=False, server_default="0"))
    op.add_column('tabs', sa.Column('last_opened_at', sa.DateTime(), nullable=True))
    op.add_column('tabs', sa.Column('last_chat_at', sa.DateTime(), nullable=True))
    op.add_column('tabs', sa.Column('chat_reference_count', sa.Integer(), nullable=False, server_default="0"))
    op.drop_index(op.f('idx_tabs_search'), table_name='tabs', postgresql_using='gin')
    op.alter_column("tabs", "importance_score", server_default=None)
    op.alter_column("tabs", "open_count", server_default=None)
    op.alter_column("tabs", "total_time_spent", server_default=None)
    op.alter_column("tabs", "chat_reference_count", server_default=None)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('idx_tabs_search'), 'tabs', [sa.literal_column("to_tsvector('english'::regconfig, (((COALESCE(title, ''::text) || ' '::text) || COALESCE(summary, ''::text)) || ' '::text) || COALESCE(content, ''::text))")], unique=False, postgresql_using='gin')
    op.drop_column('tabs', 'chat_reference_count')
    op.drop_column('tabs', 'last_chat_at')
    op.drop_column('tabs', 'last_opened_at')
    op.drop_column('tabs', 'total_time_spent')
    op.drop_column('tabs', 'open_count')
    op.drop_column('tabs', 'importance_score')
    # ### end Alembic commands ###
