"""add is_searchable to tabs

Revision ID: d48f8f999aa0
Revises: ea4de4fac2c5
Create Date: 2026-06-28 11:53:01.456063

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd48f8f999aa0'
down_revision: Union[str, Sequence[str], None] = 'ea4de4fac2c5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tabs', sa.Column('is_searchable', sa.Boolean(), nullable=True, server_default=sa.true()),)

    op.execute("""
UPDATE tabs SET is_searchable = TRUE
WHERE is_searchable IS NULL;""")
    
    op.alter_column("tabs", "is_searchable", nullable=False, server_default=None)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tabs', 'is_searchable')
    # ### end Alembic commands ###
