"""add content metadata to tabs

Revision ID: e67f11899bfa
Revises: 586fbc59f9d6
Create Date: 2026-06-16 13:11:37.965977

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e67f11899bfa'
down_revision: Union[str, Sequence[str], None] = '586fbc59f9d6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tabs', sa.Column('description', sa.Text(), nullable=True))
    op.add_column('tabs', sa.Column('word_count', sa.Integer(), nullable=False, server_default="0",))
    op.add_column('tabs', sa.Column('captured_at', sa.DateTime(), nullable=False, server_default=sa.text("CURRENT_TIMESTAMP"),),)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tabs', 'captured_at')
    op.drop_column('tabs', 'word_count')
    op.drop_column('tabs', 'description')
    # ### end Alembic commands ###
